### ISSUE TITLE
Group logo

### ISSUE THREAD

**Issue by littlepea** [littlepea/beijing-python-meetup#4]
Something like https://www.meetup.com/GreeceJS/

**Comment by idisblueflash** [comment]
I've made one similar. Is it what you want?

https://codepen.io/idisblueflash/pen/YQyLaL

**Comment by littlepea** [comment]
@idisblueflash Yes, something like that! Thanks!

**Comment by littlepea** [comment]
What do you think?
https://www.meetup.com/Beijing-Python/

**Comment by idisblueflash** [comment]
Wow～！ It's a nice starting 👍
